"""esquema inicial

Revision ID: d847ecd0e7e3
Revises:
Create Date: 2026-08-11 15:12:48.137610+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d847ecd0e7e3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corridas_ingesta",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("ingestor", sa.String(length=40), nullable=False),
        sa.Column("iniciado_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalizado_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duracion_seg", sa.Float(), nullable=True),
        sa.Column("exito", sa.Boolean(), nullable=False),
        sa.Column("filas_leidas", sa.Integer(), nullable=False),
        sa.Column("filas_nuevas", sa.Integer(), nullable=False),
        sa.Column("filas_actualizadas", sa.Integer(), nullable=False),
        sa.Column(
            "errores",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_corridas_ingesta_ingestor"), "corridas_ingesta", ["ingestor"], unique=False
    )
    op.create_index(
        "ix_corridas_ingestor_inicio", "corridas_ingesta", ["ingestor", "iniciado_at"], unique=False
    )
    op.create_table(
        "estado_sistema",
        sa.Column("clave", sa.String(length=60), nullable=False),
        sa.Column(
            "valor",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("actualizado_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("clave"),
    )
    op.create_table(
        "tickers",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industria", sa.String(length=150), nullable=True),
        sa.Column("volumen_promedio_30d", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("precio_ultimo", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("en_whitelist", sa.Boolean(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_index(op.f("ix_tickers_en_whitelist"), "tickers", ["en_whitelist"], unique=False)
    op.create_index(op.f("ix_tickers_sector"), "tickers", ["sector"], unique=False)
    op.create_table(
        "congreso_trades",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("miembro", sa.String(length=160), nullable=False),
        sa.Column("camara", sa.String(length=20), nullable=True),
        sa.Column("partido", sa.String(length=40), nullable=True),
        sa.Column("estado", sa.String(length=10), nullable=True),
        sa.Column("symbol", sa.String(length=16), nullable=True),
        sa.Column("descripcion_activo", sa.Text(), nullable=True),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("monto_min", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("monto_max", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("fecha_transaccion", sa.Date(), nullable=False),
        sa.Column("fecha_disclosure", sa.Date(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dias_retraso", sa.Integer(), nullable=True),
        sa.Column("presentacion_tardia", sa.Boolean(), nullable=False),
        sa.Column("url_filing", sa.Text(), nullable=True),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["tickers.symbol"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "miembro",
            "symbol",
            "fecha_transaccion",
            "monto_min",
            "tipo",
            name="uq_congreso_trade",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_congreso_symbol_observed", "congreso_trades", ["symbol", "observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_congreso_trades_fecha_disclosure"),
        "congreso_trades",
        ["fecha_disclosure"],
        unique=False,
    )
    op.create_index(
        op.f("ix_congreso_trades_fecha_transaccion"),
        "congreso_trades",
        ["fecha_transaccion"],
        unique=False,
    )
    op.create_index(
        op.f("ix_congreso_trades_miembro"), "congreso_trades", ["miembro"], unique=False
    )
    op.create_index(
        op.f("ix_congreso_trades_observed_at"), "congreso_trades", ["observed_at"], unique=False
    )
    op.create_table(
        "noticias",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=16), nullable=True),
        sa.Column("titulo", sa.Text(), nullable=False),
        sa.Column("resumen", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("fuente", sa.String(length=120), nullable=True),
        sa.Column("hash_contenido", sa.String(length=64), nullable=False),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sentimiento", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("confianza", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("modelo_usado", sa.String(length=60), nullable=True),
        sa.Column("es_duplicado", sa.Boolean(), nullable=False),
        sa.Column(
            "id_original", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["id_original"], ["noticias.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["symbol"], ["tickers.symbol"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash_contenido", name="uq_noticias_hash"),
    )
    op.create_index(op.f("ix_noticias_event_at"), "noticias", ["event_at"], unique=False)
    op.create_index(op.f("ix_noticias_fuente"), "noticias", ["fuente"], unique=False)
    op.create_index(op.f("ix_noticias_observed_at"), "noticias", ["observed_at"], unique=False)
    op.create_index(
        "ix_noticias_symbol_observed", "noticias", ["symbol", "observed_at"], unique=False
    )
    op.create_table(
        "posiciones_sombra",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("fecha_entrada", sa.Date(), nullable=False),
        sa.Column("precio_entrada", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("tamano_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("stop", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("fecha_salida", sa.Date(), nullable=True),
        sa.Column("precio_salida", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("motivo_salida", sa.String(length=60), nullable=True),
        sa.Column("abierta", sa.Boolean(), nullable=False),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["tickers.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_posiciones_sombra_fecha_entrada"),
        "posiciones_sombra",
        ["fecha_entrada"],
        unique=False,
    )
    op.create_index(
        "ix_sombra_symbol_abierta", "posiciones_sombra", ["symbol", "abierta"], unique=False
    )
    op.create_table(
        "precios_diarios",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("apertura", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("maximo", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("minimo", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("cierre", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("cierre_ajustado", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("volumen", sa.BigInteger(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["tickers.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "fecha", name="uq_precios_symbol_fecha"),
    )
    op.create_index(op.f("ix_precios_diarios_fecha"), "precios_diarios", ["fecha"], unique=False)
    op.create_index(
        op.f("ix_precios_diarios_observed_at"), "precios_diarios", ["observed_at"], unique=False
    )
    op.create_index(
        "ix_precios_symbol_observed", "precios_diarios", ["symbol", "observed_at"], unique=False
    )
    op.create_table(
        "reddit_diario",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("subreddit", sa.String(length=60), nullable=False),
        sa.Column("menciones", sa.Integer(), nullable=False),
        sa.Column("sentimiento_promedio", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("upvotes_totales", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["tickers.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "fecha", "subreddit", name="uq_reddit_symbol_fecha_sub"),
    )
    op.create_index(op.f("ix_reddit_diario_fecha"), "reddit_diario", ["fecha"], unique=False)
    op.create_index(
        op.f("ix_reddit_diario_observed_at"), "reddit_diario", ["observed_at"], unique=False
    )
    op.create_index(
        "ix_reddit_symbol_observed", "reddit_diario", ["symbol", "observed_at"], unique=False
    )
    op.create_table(
        "senales",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("score_total", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column(
            "componentes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("regimen_mercado", sa.String(length=20), nullable=True),
        sa.Column("version_modelo", sa.String(length=40), nullable=False),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["tickers.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "fecha", "version_modelo", name="uq_senales_symbol_fecha_ver"
        ),
    )
    op.create_index(op.f("ix_senales_fecha"), "senales", ["fecha"], unique=False)
    op.create_index("ix_senales_fecha_score", "senales", ["fecha", "score_total"], unique=False)
    op.create_table(
        "sugerencias",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("senal_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("accion", sa.String(length=20), nullable=False),
        sa.Column("precio_referencia", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("stop_sugerido", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("tamano_sugerido_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("razon", sa.Text(), nullable=True),
        sa.Column("enviada_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mensaje_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["senal_id"], ["senales.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["symbol"], ["tickers.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sugerencias_enviada_at"), "sugerencias", ["enviada_at"], unique=False)
    op.create_index(
        "ix_sugerencias_symbol_enviada", "sugerencias", ["symbol", "enviada_at"], unique=False
    )
    op.create_table(
        "ejecuciones",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "sugerencia_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("accion", sa.String(length=20), nullable=False),
        sa.Column("precio_real", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("comisiones", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("creado_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["sugerencia_id"], ["sugerencias.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["symbol"], ["tickers.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ejecuciones_fecha"), "ejecuciones", ["fecha"], unique=False)
    op.create_index("ix_ejecuciones_symbol_fecha", "ejecuciones", ["symbol", "fecha"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ejecuciones_symbol_fecha", table_name="ejecuciones")
    op.drop_index(op.f("ix_ejecuciones_fecha"), table_name="ejecuciones")
    op.drop_table("ejecuciones")
    op.drop_index("ix_sugerencias_symbol_enviada", table_name="sugerencias")
    op.drop_index(op.f("ix_sugerencias_enviada_at"), table_name="sugerencias")
    op.drop_table("sugerencias")
    op.drop_index("ix_senales_fecha_score", table_name="senales")
    op.drop_index(op.f("ix_senales_fecha"), table_name="senales")
    op.drop_table("senales")
    op.drop_index("ix_reddit_symbol_observed", table_name="reddit_diario")
    op.drop_index(op.f("ix_reddit_diario_observed_at"), table_name="reddit_diario")
    op.drop_index(op.f("ix_reddit_diario_fecha"), table_name="reddit_diario")
    op.drop_table("reddit_diario")
    op.drop_index("ix_precios_symbol_observed", table_name="precios_diarios")
    op.drop_index(op.f("ix_precios_diarios_observed_at"), table_name="precios_diarios")
    op.drop_index(op.f("ix_precios_diarios_fecha"), table_name="precios_diarios")
    op.drop_table("precios_diarios")
    op.drop_index("ix_sombra_symbol_abierta", table_name="posiciones_sombra")
    op.drop_index(op.f("ix_posiciones_sombra_fecha_entrada"), table_name="posiciones_sombra")
    op.drop_table("posiciones_sombra")
    op.drop_index("ix_noticias_symbol_observed", table_name="noticias")
    op.drop_index(op.f("ix_noticias_observed_at"), table_name="noticias")
    op.drop_index(op.f("ix_noticias_fuente"), table_name="noticias")
    op.drop_index(op.f("ix_noticias_event_at"), table_name="noticias")
    op.drop_table("noticias")
    op.drop_index(op.f("ix_congreso_trades_observed_at"), table_name="congreso_trades")
    op.drop_index(op.f("ix_congreso_trades_miembro"), table_name="congreso_trades")
    op.drop_index(op.f("ix_congreso_trades_fecha_transaccion"), table_name="congreso_trades")
    op.drop_index(op.f("ix_congreso_trades_fecha_disclosure"), table_name="congreso_trades")
    op.drop_index("ix_congreso_symbol_observed", table_name="congreso_trades")
    op.drop_table("congreso_trades")
    op.drop_index(op.f("ix_tickers_sector"), table_name="tickers")
    op.drop_index(op.f("ix_tickers_en_whitelist"), table_name="tickers")
    op.drop_table("tickers")
    op.drop_table("estado_sistema")
    op.drop_index("ix_corridas_ingestor_inicio", table_name="corridas_ingesta")
    op.drop_index(op.f("ix_corridas_ingesta_ingestor"), table_name="corridas_ingesta")
    op.drop_table("corridas_ingesta")
    # ### end Alembic commands ###
